[package]
name = "crisprme"
version = "0.1.0"
edition = "2021"

[dependencies]
crisprme-cuda = { path = "../crisprme-cuda" }
needleman = "0.2.0"
prettytable-rs = "0.10.0"
rand = "0.9.0"
shrinkwraprs = "0.3.0"
